name: update
      
on:   
  workflow_dispatch:
  schedule:
    - cron: 30 18 * * 5

jobs:
  jvs-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: fetch, parse
        run: cargo run --release
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: update
